const WHATSAPP='919710006033';
const header=document.getElementById('header'); if(header) window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>35));
const menu=document.getElementById('menu'),nav=document.getElementById('navlinks'); if(menu&&nav){menu.onclick=()=>nav.classList.toggle('open');document.querySelectorAll('.navlinks a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
const slides=[...document.querySelectorAll('.slide')],dots=[...document.querySelectorAll('.hero-dot')];let current=0,timer;
function showSlide(i){if(!slides.length)return;current=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle('active',n===current));dots.forEach((d,n)=>d.classList.toggle('active',n===current))}
function auto(){if(slides.length>1){clearInterval(timer);timer=setInterval(()=>showSlide(current+1),5500)}}
const prev=document.getElementById('prev'),next=document.getElementById('next');if(prev)prev.onclick=()=>{showSlide(current-1);auto()};if(next)next.onclick=()=>{showSlide(current+1);auto()};dots.forEach(d=>d.onclick=()=>{showSlide(+d.dataset.i);auto()});auto();
const lb=document.getElementById('lightbox'),lbImg=document.getElementById('lbImg');let li=0;const gallery=[...document.querySelectorAll('.portfolio-image')];
function openLb(i){if(!lb||!gallery.length)return;li=(i+gallery.length)%gallery.length;lbImg.src=gallery[li].src;lbImg.alt=gallery[li].alt||'';lb.classList.add('open');document.body.style.overflow='hidden'}
gallery.forEach((im,i)=>im.addEventListener('click',e=>{e.preventDefault();openLb(i)}));const close=document.querySelector('.lb-close');if(close)close.onclick=()=>{lb.classList.remove('open');document.body.style.overflow=''};document.querySelector('.lb-prev')?.addEventListener('click',()=>openLb(li-1));document.querySelector('.lb-next')?.addEventListener('click',()=>openLb(li+1));document.addEventListener('keydown',e=>{if(!lb?.classList.contains('open'))return;if(e.key==='Escape')close.click();if(e.key==='ArrowLeft')openLb(li-1);if(e.key==='ArrowRight')openLb(li+1)});
const form=document.getElementById('bookingForm');if(form)form.addEventListener('submit',e=>{e.preventDefault();const n=document.getElementById('name').value,p=document.getElementById('phone').value,ev=document.getElementById('event').value,m=document.getElementById('message').value;const text=`Hello UDHAYASTUDIOZ!\n\nName: ${n}\nPhone: ${p}\nEvent/Date: ${ev}\nMessage: ${m}`;window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(text)}`,'_blank')});
